-- Create a table for public profiles
create table profiles (
  id uuid references auth.users on delete cascade not null,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,
  bio text,
  role text check (role in ('talent', 'project')),
  primary_skill text,
  skills text,

  primary key (id),
  unique(username),
  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Gigs Table (Freelance)
create table gigs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  owner_id uuid references auth.users not null,
  title text not null,
  description text not null,
  budget text,
  duration text,
  tags text[],
  status text default 'open' check (status in ('open', 'closed', 'in_progress'))
);

alter table gigs enable row level security;

create policy "Gigs are viewable by everyone."
  on gigs for select
  using ( true );

create policy "Users can create gigs."
  on gigs for insert
  with check ( auth.role() = 'authenticated' );
  
create policy "Owners can update their gigs."
  on gigs for update
  using ( auth.uid() = owner_id );

-- Messages Table
create table messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  sender_id uuid references auth.users not null,
  receiver_id uuid references auth.users not null,
  content text not null,
  is_read boolean default false
);

alter table messages enable row level security;

create policy "Users can see their own messages."
  on messages for select
  using ( auth.uid() = sender_id or auth.uid() = receiver_id );

create policy "Users can insert messages."
  on messages for insert
  with check ( auth.uid() = sender_id );

-- Applications Table
create table applications (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  applicant_id uuid references auth.users not null,
  job_id text not null, -- Can reference gigs.id or external project ID
  job_type text not null, -- 'gig' or 'project'
  cover_letter text,
  status text default 'pending'
);

alter table applications enable row level security;

create policy "Users can see their own applications."
  on applications for select
  using ( auth.uid() = applicant_id );

create policy "Users can create applications."
  on applications for insert
  with check ( auth.uid() = applicant_id );
