-- Create a table for public profiles
create table profiles (
  id uuid references auth.users on delete cascade not null,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,
  bio text,
  role text check (role in ('talent', 'project')),
  primary_skill text,
  skills text[],

  primary key (id),
  unique(username),
  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Gigs Table (Freelance)
create table gigs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  owner_id uuid references auth.users not null,
  title text not null,
  description text not null,
  budget text,
  duration text,
  tags text[],
  status text default 'open' check (status in ('open', 'closed', 'in_progress'))
);

alter table gigs enable row level security;

create policy "Gigs are viewable by everyone."
  on gigs for select
  using ( true );

create policy "Users can create gigs."
  on gigs for insert
  with check ( auth.role() = 'authenticated' );
  
create policy "Owners can update their gigs."
  on gigs for update
  using ( auth.uid() = owner_id );

-- Jobs Table (Full-time / Contract Roles)
create table jobs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  project_id uuid references auth.users not null,
  title text not null,
  description text not null,
  salary_range text,
  type text check (type in ('full-time', 'contract', 'freelance', 'dao')),
  location text,
  requirements text, -- structured text or JSON
  status text default 'open' check (status in ('open', 'closed'))
);

alter table jobs enable row level security;

create policy "Jobs are viewable by everyone."
  on jobs for select
  using ( true );

create policy "project can insert jobs."
  on jobs for insert
  with check ( auth.role() = 'authenticated' ); --Ideally check for 'project' role in a trigger or app logic

create policy "project can update their own jobs."
  on jobs for update
  using ( auth.uid() = project_id );

-- Conversations Table (Group messages)
create table conversations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  participant1_id uuid references auth.users not null,
  participant2_id uuid references auth.users not null,
  last_message text,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(participant1_id, participant2_id)
);

alter table conversations enable row level security;

create policy "Users can see their own conversations."
  on conversations for select
  using ( auth.uid() = participant1_id or auth.uid() = participant2_id );

create policy "Users can create conversations."
  on conversations for insert
  with check ( auth.role() = 'authenticated' );

create policy "Participants can update conversations."
  on conversations for update
  using ( auth.uid() = participant1_id or auth.uid() = participant2_id );

-- Messages Table
create table messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  sender_id uuid references auth.users not null,
  receiver_id uuid references auth.users not null, -- Optional if using conversation_id, but good for quick lookup
  conversation_id bigint references conversations(id) on delete cascade not null,
  content text not null,
  is_read boolean default false
);

alter table messages enable row level security;

create policy "Users can see their own messages."
  on messages for select
  using ( auth.uid() = sender_id or auth.uid() = receiver_id );

create policy "Users can insert messages."
  on messages for insert
  with check ( auth.uid() = sender_id );

-- RPC to get conversation ID or create one (optional, but useful)
-- For now we handle logic in frontend


-- Applications Table
create table applications (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  applicant_id uuid references auth.users not null,
  job_id bigint references jobs(id), -- Nullable if we support other types, or specific
  gig_id bigint references gigs(id), -- Optional: link to gig if it's a gig application
  job_type text default 'job', -- 'gig' or 'job'
  cover_letter text,
  status text default 'pending',
  unique(applicant_id, job_id) -- Prevent double application
);

alter table applications enable row level security;

create policy "Users can see their own applications."
  on applications for select
  using ( auth.uid() = applicant_id );

create policy "Users can create applications."
  on applications for insert
  with check ( auth.uid() = applicant_id );

-- Notifications Table
create table notifications (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  type text check (type in ('message', 'application', 'system')),
  content text not null,
  link text,
  is_read boolean default false
);

alter table notifications enable row level security;

create policy "Users can see their own notifications."
  on notifications for select
  using ( auth.uid() = user_id );

create policy "Authenticated users can insert notifications."
  on notifications for insert
  with check ( auth.role() = 'authenticated' );

create policy "Users can update their own notifications."
  on notifications for update
  using ( auth.uid() = user_id );
